# Generated by Django 3.0.7 on 2020-06-18 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200611_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='career',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.Career'),
        ),
    ]
