# Generated by Django 3.0.7 on 2020-06-18 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200618_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='profie',
            new_name='profile',
        ),
    ]
