# Generated by Django 3.0.7 on 2020-06-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200611_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='is_follow',
            field=models.BooleanField(default=False),
        ),
    ]
