# Generated by Django 3.0.7 on 2020-06-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='educations',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='languages',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='other_experiences',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_experiences',
            field=models.TextField(null=True),
        ),
    ]
