# Generated by Django 3.0.7 on 2020-06-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200611_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
