# Generated by Django 3.0.7 on 2020-06-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_subcategory_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
